### ISSUE TITLE
More info required

### ISSUE THREAD

**Issue by VishnAndr** [SAP-Cloud-Platform-Integration/notify#1]
Hi SAP Cloud Platform Integration,

This project seems to be interesting. Keen to help with development / testing. Can we get more information on how it supposed to work? Thanks.

Cheers,
Andrei

**Comment by Soontao** [comment]
Hi @VishnAndr 

I've updated the README page to provide more information. 
In short, this project just want to impl the notification feature for CPI without UI, and the programming language is `golang`.

Splitting more tasks is difficult because it's a simple project, just polling the API and sending emails.
And I'll finish this project & release the binary in this week, maybe you could provide some suggesting make it easier to use after first release.

Thanks, 
Theo
